openapi: 3.2.0
info:
  title: Number Verify - KPN Insights API
  description: With KPN Number Verify, you can quickly check whether the mobile number someone provides is the same as their SIM card.
  contact:
    name: API Support
    email: api_developer@kpn.com
    url: https://developer.kpn.com/support
  termsOfService: https://developer.kpn.com/legal
  version: 1.2.1
servers:
- url: https://api-prd.kpn.com/communication/kpn/numberverify
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/kpn/NumberVerify-KPN/1.2.1
tags:
- name: Insights
paths:
  /insights/{msisdn}:
    post:
      summary: Insights Request
      parameters:
      - name: msisdn
        in: path
        required: true
        schema:
          type: string
          example: '31630000001'
      requestBody:
        required: true
        content:
          application/json:
            examples:
              polling:
                summary: Polling Example
                description: Body can be empty for polling
                value: {}
              notification:
                summary: Notification Example
                description: '- You will need to pass the “notification_token” which is used as the “bearer” token when posting the results to “notification_uri.”

                  - To see the notification in the provided webhook, the session_uri must be accessed.

                  '
                value:
                  device_match_notify:
                    notification_token: abcd1234
                    notification_uri: https://your_webhook_url/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/InsightsResponse'
                - $ref: '#/components/schemas/InsightsResponseNotify'
              examples:
                polling:
                  summary: Polling Example
                  value:
                    device_match:
                      session_id: e46714d908600d8cf9f3abbf9f4056ff
                      polling_id: e46714d908600d8cf9f3abbf9f4056ff
                    operator_lookup:
                      regionCode: NL
                      operatorName: KPN
                      mcc: null
                      mnc: null
                notification:
                  summary: Notification Example
                  description: '- You will need to pass the “notification_token” which is used as the “bearer” token when posting the results to “notification_uri.”

                    - To see the notification in the provided webhook, the session_uri must be accessed.

                    '
                  value:
                    device_match_notify:
                      session_uri: http://server/v1/dm/session/5f563a0bbb61c93748f773b744bf19c6
                    operator_lookup:
                      regionCode: NL
                      operatorName: KPN
                      mcc: null
                      mnc: null
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - BearerAuth: []
      tags:
      - Insights
      operationId: postInsightsByMsisdn
      x-operation-id-source: derived
components:
  schemas:
    InsightsResponseNotify:
      type: object
      properties:
        device_match_notify:
          type: object
          properties:
            session_uri:
              type: string
              example: http://server/v1/dm/session/5f563a0bbb61c93748f773b744bf19c6
          description: To see the notification in the provided webhook, the session_uri must be accessed. Also, notification would work as expected only when the scopes have device_match_notify.
        operator_lookup:
          type: object
          properties:
            regionCode:
              type: string
              example: NL
            operatorName:
              type: string
              example: KPN
            mcc:
              type:
              - string
              - 'null'
              example: null
    Error:
      type: object
      properties:
        error_code:
          type: integer
          description: HTTP status code representing the error
          example: 400
          enum:
          - 400
          - 401
          - 403
          - 404
          - 405
          - 412
          - 429
          - 500
          - 502
          - 503
        message:
          type: string
          description: A short description of the error
          example: Bad Request
          enum:
          - Bad Request
          - Unauthorized
          - Forbidden
          - Not Found
          - Method Not Allowed
          - Precondition Failed
          - Too Many Requests
          - Internal Server Error
          - Bad Gateway
          - Service Unavailable
    InsightsResponse:
      type: object
      properties:
        device_match:
          type: object
          properties:
            session_uri:
              type: string
              example: http://server/v1/dm/session/e46714d908600d8cf9f3abbf9f4056ff
            polling_uri:
              type: string
              example: https://server/v1/dm/polling/e46714d908600d8cf9f3abbf9f4056ff
          description: Polling would only work when the /token flow has device_match in scopes, and notification would work as expected only when the scopes have device_match_notify. operator_lookup works in both examples.
        operator_lookup:
          type: object
          properties:
            regionCode:
              type: string
              example: NL
            operatorName:
              type: string
              example: KPN
            mcc:
              type:
              - string
              - 'null'
              example: null
            mnc:
              type:
              - string
              - 'null'
              example: null
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
